version: '3.8'

networks:
  openhim:
    external: true

services:
  dhis2-pass-through-mediator:
    build: .
    container_name: dhis2-pass-through-mediator
    networks:
      - openhim
    ports:
      - 3000:3000
    env_file:
      - .env